- name: Ensure .aws dir exists
  file:
    path: ~/.aws
    state: directory
    mode: '0700'

- name: Create aws credentials
  template:
    src: credentials.j2
    dest: ~/.aws/credentials
    mode: '0600'
    backup: yes
