apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
    deploymentconfig: grafana
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
