#- name: Remove worker label from infra nodes
#  k8s:
#    api_version: v1
#    kind: Node
#    name: "{{ item }}"
#    definition:
#      metadata:
#        labels:
#          node-role.kubernetes.io/worker: null
#  with_items: "{{ infra_list | json_query('resources[].metadata.name') }}"

#- name: Remove worker label from ocs nodes
#  k8s:
#    api_version: v1
#    kind: Node
#    name: "{{ item }}"
#    definition:
#      metadata:
#        labels:
#          node-role.kubernetes.io/worker: null
#  with_items: "{{ ocs_list | json_query('resources[].metadata.name') }}"

- name: Create MachineConfigPool infra
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: infra
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra]}
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/infra: ""

- name: Create MachineConfigPool ocs
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: ocs
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,ocs]}
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/ocs: ""

- name: Config allocated resources for nodes
  block:
    - name: Label MCPs
      k8s:
        api_version: machineconfiguration.openshift.io/v1
        kind: MachineConfigPool
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              custom-kubelet: allocatable
      loop:
        - master
        - worker
    - name: Create KubeletConfig
      k8s:
        state: present
        definition:
          apiVersion: machineconfiguration.openshift.io/v1
          kind: KubeletConfig
          metadata:
            name: allocatable
          spec:
            machineConfigPoolSelector:
              matchLabels:
                custom-kubelet: allocatable
            kubeletConfig:
              kubeAPIBurst: 1000
              kubeAPIQPS: 500
              kubeReserved:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 1Gi
              systemReserved:
                cpu: 500m
                memory: 1Gi
                ephemeral-storage: 1Gi

- name: Move registry to infra nodes and scale up to 3
  k8s:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
    definition:
      spec:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
        - effect: NoSchedule
          key: infra
          value: reserved
        - effect: NoExecute
          key: infra
          value: reserved

- name: Move routers to infra nodes, scale up to 3 and with letsencrypt
  k8s:
    api_version: operator.openshift.io/v1
    kind: IngressController
    namespace: openshift-ingress-operator
    name: default
    definition:
      spec:
        defaultCertificate:
          name: router-certs-letsencrypt
        replicas: 3
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved
        logging:
          access:
            destination:
              type: Container

