- name: OCP HA Lab - Post-installation Setup
  hosts: localhost,masters[0]
  order: inventory

  roles:
    - role: get-kubecfg
      when: inventory_hostname == groups['masters'][0]
    - role: pause
    - role: groupsync
      when: inventory_hostname == groups['masters'][0]
    - role: config-metrics
      when: inventory_hostname == groups['masters'][0]
    - role: set-default-sc
      when: inventory_hostname == groups['masters'][0]
