- name: OCP HA Lab - Pre-installation Setup
  hosts: localhost,all
  order: inventory
  vars_prompt:
    - name: rhnpasswd
      prompt: "RHN Password"
      private: yes

  roles:
    - role: set-guid
    - role: set-env
      when: inventory_hostname == 'localhost'
    - role: get-ipa-ca
      when: inventory_hostname == 'localhost'
    - role: create-inventory
      when: inventory_hostname == 'localhost'
    - role: setup-nfs
      when: inventory_hostname in groups['nfs']
    - role: reg-host
      when: inventory_hostname != 'localhost'
    - role: updatereboot
      when: inventory_hostname != 'localhost'
