- name: OCP HA Lab - Pre-installation Setup
  hosts: localhost,all
  order: inventory

  roles:
    - role: set-guid
    - role: set-env
      when: inventory_hostname == 'localhost'
    - role: get-ipa-ca
      when: inventory_hostname == 'localhost'
    - role: create-inventory
      when: inventory_hostname == 'localhost'
    - role: setup-nfs
      when: inventory_hostname in groups['nfs']
#   - role: set-manage_cgroup
#     when: inventory_hostname in groups['nodes']
    - role: wipe-disk
      when: inventory_hostname_short == 'node1' or inventory_hostname_short == 'node2' or inventory_hostname_short == 'node3'
    - role: updatereboot
#     when: inventory_hostname != 'localhost'
