- name: set vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: set vi alias
  lineinfile:
    path: ~/.bashrc
    line: 'alias vi=vim'
    insertafter: '^alias mv'

- name: set env vars
  lineinfile:
    path: ~/.bash_profile
    line: "{{ item }}"
  with_items:
    - ''
    - 'EDITOR=vim'
    - 'VISUAL=vim'
    - 'export EDITOR VISUAL'

- name: create ~/bin
  file:
    path: ~/bin
    state: directory

- name: get jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    dest: ~/bin/jq
    mode: '0755'

- name: get yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
    dest: ~/bin/yq
    mode: '0755'

