- name: Update repo to newer dir
  replace:
    path: /etc/yum.repos.d/open_ocp-ha-lab.repo
    regexp: '3\.11\.59'
    replace: '3.11.153'

- name: clear versionlock
  command: yum versionlock clear
  when: inventory_hostname in groups['nodes']

- name: yum clean all
  command: yum clean all

- name: docker unexclude
  command: /sbin/atomic-openshift-docker-excluder unexclude
  when: inventory_hostname in groups['nodes']

- name: openshift unexclude
  command: /sbin/atomic-openshift-excluder unexclude
  when: inventory_hostname in groups['nodes']

- name: yum update all
  yum:
    name: '*'
    state: latest

- name: docker exclude
  command: /sbin/atomic-openshift-docker-excluder exclude
  when: inventory_hostname in groups['nodes']

- name: openshift exclude
  command: /sbin/atomic-openshift-excluder exclude
  when: inventory_hostname in groups['nodes']

- name: docker-storage-setup DEVS
  lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    regexp: '^DEVS'
    state: absent
  when: inventory_hostname_short == 'node1' or inventory_hostname_short == 'node2' or inventory_hostname_short == 'node3'

- name: docker-storage-setup VG
  lineinfile:
    path: /etc/sysconfig/docker-storage-setup
    regexp: '^VG'
    state: absent
  when: inventory_hostname_short == 'node1' or inventory_hostname_short == 'node2' or inventory_hostname_short == 'node3'

- name: wipe xvdb
  command: /usr/sbin/wipefs -f -a /dev/xvdb
  when: inventory_hostname_short == 'node1' or inventory_hostname_short == 'node2' or inventory_hostname_short == 'node3'

- name: parted
  parted:
    device: /dev/xvdb
    label: gpt
  when: inventory_hostname_short == 'node1' or inventory_hostname_short == 'node2' or inventory_hostname_short == 'node3'

- name: Reboot
  shell: sleep 3 && /sbin/shutdown -r now
  async: 60
  poll: 0
  when: inventory_hostname != 'localhost'

- name: Wait for the server to boot up
  wait_for_connection:
    delay: 60
  when: inventory_hostname != 'localhost'
