- name: yum update all
  yum:
    name: '*'
    state: latest

- name: Reboot
  shell: sleep 3 && /sbin/shutdown -r now
  async: 60
  poll: 0

- name: Wait for the server to boot up
  wait_for_connection:
    delay: 60
