- name: Update repo to newer dir
  replace:
    path: /etc/yum.repos.d/open_ocp-ha-lab.repo
    regexp: '3\.11\.59'
    replace: '3.11.154'

- name: docker unexclude
  command: /sbin/atomic-openshift-docker-excluder unexclude
  when: inventory_hostname in groups['nodes']

- name: openshift unexclude
  command: /sbin/atomic-openshift-excluder unexclude
  when: inventory_hostname in groups['nodes']

- name: yum update all
  yum:
    name: '*'
    state: latest

- name: docker exclude
  command: /sbin/atomic-openshift-docker-excluder exclude
  when: inventory_hostname in groups['nodes']

- name: openshift exclude
  command: /sbin/atomic-openshift-excluder exclude
  when: inventory_hostname in groups['nodes']

- name: Reboot
  shell: sleep 3 && /sbin/shutdown -r now
  async: 60
  poll: 0
  when: inventory_hostname != 'localhost'

- name: Wait for the server to boot up
  wait_for_connection:
    delay: 60
  when: inventory_hostname != 'localhost'
