ocpver: 4.7.13
ocschannel: 4.7
maistraver: 2.0
certmgrver: 1.3.1
yqver: 4.9.3
guid: "{{ ansible_nodename.split('.')[1] }}"
config:
  instance_type: m5
  multitenant: false
  installer_ssh_key: "{{ lookup('file', '~/.ssh/cluster-{{ guid }}-key.pub') }}"
  pull_secret: "{{ lookup('file', '~/pull-secret') }}"
