ocpver: 4.7.8
ocschannel: 4.6
guid: "{{ ansible_nodename.split('.')[1] }}"
config:
  multitenant: false
  installer_ssh_key: "{{ lookup('file', '~/.ssh/cluster-{{ guid }}-key.pub') }}"
  pull_secret: "{{ lookup('file', '~/pull-secret') }}"
