- name: Install OCS
  block:
    - name: Create openshift-storage namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-storage
            annotations:
              openshift.io/node-selector: ""
            labels:
              openshift.io/cluster-monitoring: "true"
    - name: Create openshift-storage OperatorGroup
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: openshift-storage
            namespace: openshift-storage
          spec:
            targetNamespaces:
              - openshift-storage
    - name: Create ocs-operator Subscription
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: ocs-operator
            namespace: openshift-storage
          spec:
            channel: "stable-{{ ocschannel }}"
            installPlanApproval: Automatic
            name: ocs-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
        wait: yes
        wait_condition:
          reason: AllCatalogSourcesHealthy
          type: CatalogSourcesUnhealthy
          status: "False"
    - name: Get ocs-operator Subscription info
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: ocs-operator
        namespace: openshift-storage
      register: ocs_sub_info
    - name: Wait for successful ocs-operator CSV
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ ocs_sub_info.resources[0].status.currentCSV }}"
        namespace: openshift-storage
      register: ocs_csv_info
      until: ocs_csv_info.resources[0].status.phase == "Succeeded"
      retries: 10
      delay: 3
    - name: Create StorageCluster
      k8s:
        state: present
        definition: "{{ lookup('file', 'ocs-storagecluster.yml') }}"
    - name: Fix DaemonSets tolerations
      k8s:
        api_version: v1
        kind: ConfigMap
        name: rook-ceph-operator-config
        namespace: openshift-storage
        definition: "{{ lookup('file', 'rook-ceph-operator-config.yml') }}"
