- name: Create manifests
  command: openshift-install create manifests --dir $HOME/cluster-${GUID}

- name: Create cluster-network-03-config
  copy:
    src: cluster-network-03-config.yml
    dest: ~/cluster-{{ guid.stdout }}/manifests
    mode: 0640

- name: Create infra machinesets
  copy:
    src: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_worker-machineset-{{ item }}.yaml
    dest: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    mode: 0640
  with_sequence: start=0 end=2

- name: Switch to m4.xlarge
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    regexp: 'm4\.large'
    replace: 'm4.xlarge'
  with_sequence: start=0 end=2

- name: Update infra machinesets part1
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    regexp: '-worker-us'
    replace: '-infra-us'
  with_sequence: start=0 end=2

- name: Update infra machinesets part2
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    regexp: 'worker$'
    replace: 'infra'
  with_sequence: start=0 end=2

- name: Insert infra node labels
  lineinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item[0] }}.yaml
    line: "{{ item[1] }}"
    insertbefore: '^      providerSpec:$'
  with_nested:
    - ['0', '1', '2']
    - ['        labels:', '          node-role.kubernetes.io/infra: ""']

- name: Insert infra node taints
  blockinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    insertbefore: '^      providerSpec:$'
    block: |6
          taints:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved
  with_sequence: start=0 end=2

