- name: Create manifests
  command: openshift-install create manifests --dir $HOME/cluster-${GUID}

- name: Create cluster-network-03-config
  copy:
    src: cluster-network-03-config.yml
    dest: ~/cluster-{{ guid.stdout }}/manifests
    mode: 0640

- name: Create infra and ocs machinesets
  copy:
    src: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_worker-machineset-{{ item.0 }}.yaml
    dest: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_{{ item.1 }}-machineset-{{ item.0 }}.yaml
    mode: 0640
  with_nested:
    - ['0', '1', '2']
    - ['infra', 'ocs']

- name: Switch to m4.xlarge
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_{{ item.1 }}-machineset-{{ item.0 }}.yaml
    regexp: 'm4\.large'
    replace: 'm4.xlarge'
  with_nested:
    - ['0', '1', '2']
    - ['infra', 'ocs']

- name: Update infra and ocs machinesets part1
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_{{ item.1 }}-machineset-{{ item.0 }}.yaml
    regexp: '-worker-us'
    replace: '-{{ item.1 }}-us'
  with_nested:
    - ['0', '1', '2']
    - ['infra', 'ocs']

- name: Update infra and ocs machinesets part2
  replace:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_{{ item.1 }}-machineset-{{ item.0 }}.yaml
    regexp: 'worker$'
    replace: '{{ item.1 }}'
  with_nested:
    - ['0', '1', '2']
    - ['infra', 'ocs']

- name: Insert infra node labels
  lineinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item.0 }}.yaml
    line: "{{ item.1 }}"
    insertbefore: '^      providerSpec:$'
  with_nested:
    - ['0', '1', '2']
    - ['        labels:', '          node-role.kubernetes.io/infra: ""']

- name: Insert ocs node labels
  lineinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_ocs-machineset-{{ item.0 }}.yaml
    line: "{{ item.1 }}"
    insertbefore: '^      providerSpec:$'
  with_nested:
    - ['0', '1', '2']
    - ['        labels:', '          node-role.kubernetes.io/ocs: ""', '          cluster.ocs.openshift.io/openshift-storage: ""']

- name: Insert infra node taints
  blockinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_infra-machineset-{{ item }}.yaml
    insertbefore: '^      providerSpec:$'
    block: |2
            taints:
            - effect: NoSchedule
              key: infra
              value: reserved
            - effect: NoExecute
              key: infra
              value: reserved
  with_sequence: start=0 end=2

- name: Insert ocs node taints
  blockinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_ocs-machineset-{{ item }}.yaml
    insertbefore: '^      providerSpec:$'
    block: |2
            taints:
            - effect: NoSchedule
              key: node.ocs.openshift.io/storage
              value: "true"
  with_sequence: start=0 end=2

- name: Remove infra and ocs managed block lines
  lineinfile:
    path: ~/cluster-{{ guid.stdout }}/openshift/99_openshift-cluster-api_{{ item.1 }}-machineset-{{ item.0 }}.yaml
    line: "{{ item.2 }}"
    state: absent
  with_nested:
    - ['0', '1', '2']
    - ['infra', 'ocs']
    - ['# BEGIN ANSIBLE MANAGED BLOCK', '# END ANSIBLE MANAGED BLOCK']

- name: Set nodeplacement for ingress
  blockinfile:
    path: ~/cluster-{{ guid.stdout }}/manifests/cluster-ingress-02-config.yml
    insertafter: '^spec:$'
    block: |2
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved

- name: Remove ingress managed block lines
  lineinfile:
    path: ~/cluster-{{ guid.stdout }}/manifests/cluster-ingress-02-config.yml
    line: "{{ item }}"
    state: absent
  loop:
    - "# BEGIN ANSIBLE MANAGED BLOCK"
    - "# END ANSIBLE MANAGED BLOCK"

