- name: Create OCP4 Cluster
  hosts: localhost
  order: inventory

  pre_tasks:
    - name: Get hosted zones
      route53_info:
        query: hosted_zone
      register: hosted_zones
    - name: Get sandbox id
      set_fact:
        sbid: "{{ (hosted_zones | json_query('HostedZones[].Name | [?starts_with(@, `sandbox`)] | [0]')).split('.')[0].split('x')[1] }}"
    - name: Check if cluster-guid-key.pub exists
      fail:
        msg: "Error: Please provide cluster-{{ guid }}-key.pub!"
      when: config.installer_ssh_key is none or config.installer_ssh_key == ""
    - name: Check if pull-secret.json exists
      fail:
        msg: "Error: Please provide pull-secret.json!"
      when: config.pull_secret is none or config.pull_secret == ""
    - name: Get installer version
      command: openshift-install version
      register: ocp_install_ver

  roles:
    - role: create-install-config
    - role: create-manifests
