- name: Create OCP4 Cluster
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: sbid
      prompt: "sandbox id"
      private: no

  pre_tasks:
    - name: Get GUID
      shell: hostname | cut -d"." -f2
      register: guid

  roles:
    - role: create-install-config
