- name: Create OCP4 Cluster
  hosts: localhost
  order: inventory

  pre_tasks:
    - name: Get hosted zones
      route53_info:
        query: hosted_zone
      register: hosted_zones
    - name: Get base domain
      set_fact:
        # Needs to and from due to https://github.com/ansible/ansible/issues/27299
        base_domain: "{{ (hosted_zones | to_json | from_json | json_query('HostedZones[].Name | [?starts_with(@, `sandbox`)] | [0]'))[:-1] }}"
    - name: Check if cluster-guid-key.pub exists
      fail:
        msg: "Error: Please provide cluster-{{ guid }}-key.pub!"
      when: config.installer_ssh_key is none or config.installer_ssh_key == ""
    - name: Check if pull-secret.json exists
      fail:
        msg: "Error: Please provide pull-secret.json!"
      when: config.pull_secret is none or config.pull_secret == ""
    - name: Get installer version
      command: openshift-install version
      register: ocp_install_ver

  roles:
    - role: create-install-config
    - role: create-manifests
