- name: Create OCP4 Cluster
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: sbid
      prompt: "sandbox id"
      private: no
    - name: multitenant
      prompt: "Use Multitenant plug-in (yes/no)"
      private: no
      default: no

  pre_tasks:
    - name: Check if pull-secret.json exists
      fail:
        msg: "Error: Please provide pull-secret.json!"
      when: pull_secret is none or pull_secret == ""
    - name: Get installer version
      command: openshift-install version
      register: ocp_install_ver

  roles:
    - role: create-install-config
    - role: create-manifests
