- name: Create OCP4 Cluster
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: sbid
      prompt: "sandbox id"
      private: no
    - name: multitenant
      prompt: "Use Multitenant plug-in (yes/no)"
      private: no
      default: no

  pre_tasks:
    - name: Get GUID
      set_fact:
        guid: "{{ ansible_nodename.split('.')[1] }}"

  roles:
    - role: create-install-config
    - role: create-manifests
