- name: Post-installation Configuration
  hosts: localhost
  order: inventory

  pre_tasks:
    - name: Get GUID
      shell: hostname | cut -d"." -f2
      register: guid

  roles:
    - role: post-install
