- name: Post-installation Configuration
  hosts: localhost
  order: inventory

  pre_tasks:
    - name: Prep all variables
      block:
        - name: Get a list of infra nodes
          k8s_info:
            kind: Node
            label_selectors:
              - node-role.kubernetes.io/infra
          register: infra_list
        - name: Get a list of ocs nodes
          k8s_info:
            kind: Node
            label_selectors:
              - node-role.kubernetes.io/ocs
          register: ocs_list
        - name: Get ClusterVersion
          k8s_info:
            api_version: config.openshift.io/v1
            kind: ClusterVersion
            name: version
          register: clusterversion
        - name: Set ClusterVersion x.y
          set_fact:
            cver_xy: "{{ clusterversion.resources[0].spec.channel.split('-')[1] }}"
        - name: Set kdesch_yml
          set_fact:
            kdesch_yml: "{{ cver_xy is version('4.7', '>=') | ternary('kube-descheduler.yml', 'kube-descheduler-old.yml') }}"
        - name: Get Infrastructure
          k8s_info:
            api_version: config.openshift.io/v1
            kind: Infrastructure
            name: cluster
          register: infra_info
        - name: Get Network Operator
          k8s_info:
            api_version: operator.openshift.io/v1
            kind: Network
            name: cluster
          register: network_op

  roles:
    - role: post-install
    - role: ocs
      tags:
        - ocs
    - role: ossm
      tags:
        - ossm
    - role: cert-manager
      tags:
        - certmgr
    - role: post-install-disruptive
