- name: OCP 4 Installation - Setup Bastion
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: awsaccesskey
      prompt: "aws_access_key_id"
      private: no
    - name: awssecretaccesskey
      prompt: "aws_secret_access_key"
      private: no

  roles:
    - role: aws-creds
    - role: set-env

  tasks:
    - name: Setup aws and ocp tools
      block:
        - name: Unzip awscli
          unarchive:
            src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
            dest: "~"
            remote_src: yes
        - name: Install AWS CLI
          command: ~/aws/install -u
        - name: Clean up files
          file:
            path: "~/{{ item }}"
            state: absent
          with_items:
            - aws
            - awscli-exe-linux-x86_64.zip
        - name: Get OCP Installer
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-install-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Get OCP Client
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-client-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Set bash completion
          shell: /usr/bin/oc completion bash > /etc/bash_completion.d/openshift
        - name: Get boto and yq
          pip:
            name: "{{ item }}" 
            executable: pip3
          loop:
            - boto
            - yq
      become: true
    - name: Setup ssh keypair
      openssh_keypair:
        path: ~/.ssh/cluster-{{ guid }}-key
