- name: OCP 4 Installation - Setup Bastion
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: ocpver
      prompt: "OCP 4 Version"
      private: no

  tasks:
    - name: Setup
      block:
        - name: Unzip awscli-bundle
          unarchive:
            src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
            dest: "~"
            remote_src: yes
        - name: Install AWS CLI
          command: ~/awscli-bundle/install -i /usr/local/aws -b /bin/aws
        - name: Clean up files
          file:
            path: "~/{{ item }}"
            state: absent
          with_items:
            - awscli-bundle
            - awscli-bundle.zip
        - name: Get OCP Installer
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-install-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Get OCP Client
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-client-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Set bash completion
          shell: /usr/bin/oc completion bash > /etc/bash_completion.d/openshift
      become: true

