- name: OCP 4 Installation - Setup Bastion
  hosts: localhost
  order: inventory
  vars_prompt:
    - name: ocpver
      prompt: "OCP 4 Version x.y.z"
      private: no
    - name: awsaccesskey
      prompt: "aws_access_key_id"
      private: no
    - name: awssecretaccesskey
      prompt: "aws_secret_access_key"
      private: no

  tasks:
    - name: Get GUID
      shell: hostname | cut -d"." -f2
      register: guid
    - name: Setup aws and ocp tools
      block:
        - name: Unzip awscli-bundle
          unarchive:
            src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
            dest: "~"
            remote_src: yes
        - name: Install AWS CLI
          command: ~/awscli-bundle/install -i /usr/local/aws -b /bin/aws
        - name: Clean up files
          file:
            path: "~/{{ item }}"
            state: absent
          with_items:
            - awscli-bundle
            - awscli-bundle.zip
        - name: Get OCP Installer
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-install-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Get OCP Client
          unarchive:
            src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocpver }}/openshift-client-linux-{{ ocpver }}.tar.gz
            dest: /usr/bin
            remote_src: yes
            exclude: README.md
        - name: Set bash completion
          shell: /usr/bin/oc completion bash > /etc/bash_completion.d/openshift
      become: true
    - name: Setup ssh keypair
      openssh_keypair:
        path: ~/.ssh/cluster-{{ guid.stdout }}-key
    - name: Set kubeconfig
      lineinfile:
        path: ~/.bash_profile
        line: 'export KUBECONFIG=~/cluster-${GUID}/auth/kubeconfig'
        insertafter: EOF

  roles:
    - role: aws-creds
    - role: set-env
