- name: Update Repos
  hosts: localhost
  order: inventory
  become: yes
  vars_prompt:
    - name: rhnpasswd
      prompt: "RHN Password"
      private: yes
    - name: ocpver
      prompt: "OCP 4 Version x.y"
      private: no

  roles:
    - role: reg-host

  tasks:
    - name: dnf update all
      dnf:
        name: '*'
        state: latest
