- name: Update Repos
  hosts: localhost
  order: inventory
	become: yes
  vars_prompt:
    - name: rhnpasswd
      prompt: "RHN Password"
      private: yes

  roles:
    - role: reg-host

  tasks:
    - name: yum clean all
      command: yum clean all
    - name: yum update all
      yum:
        name: '*'
        state: latest
