- name: Set default storageclass
	k8s:
		state: present
		api_version: storage.k8s.io/v1
		kind: StorageClass
		name: glusterfs-storage
		definition:
			metadata:
				annotations:
					storageclass.kubernetes.io/is-default-class: "true"
