- name: Remove cluster-$GUID dir
  file:
    path: ~/cluster-{{ guid.stdout }}
    state: absent

- name: Create cluster-$GUID dir
  file:
    path: ~/cluster-{{ guid.stdout }}
    state: directory

- name: Create install-config.yaml
  template:
    src: install-config.j2
    dest: ~/cluster-{{ guid.stdout }}/install-config.yaml
