- name: Get a list of infra nodes
  k8s_info:
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/infra
  register: infranode_list

- name: Remove worker label from infra nodes
  k8s:
    api_version: v1
    kind: Node
    name: "{{ item }}"
    definition:
      metadata:
        labels:
          node-role.kubernetes.io/worker: null
  with_items: "{{ infranode_list | json_query('resources[].metadata.name') }}"

- name: Create MachineConfigPool infra
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: infra
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra]}
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/infra: ""

- name: Move routers to infra nodes and scale up to 3
  k8s:
    api_version: operator.openshift.io/v1
    kind: IngressController
    namespace: openshift-ingress-operator
    name: default
    definition:
      spec:
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved
        replicas: 3

- name: Move registry to infra nodes and scale up to 3
  k8s:
    api_version: imageregistry.operator.openshift.io/v1
    kind: Config
    name: cluster
    definition:
      spec:
        replicas: 3
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
        - effect: NoSchedule
          key: infra
          value: reserved
        - effect: NoExecute
          key: infra
          value: reserved

- name: Move cluster-monitoring stack to infra nodes and add persistent storage
  k8s:
    state: present
    definition: "{{ lookup('file', 'cluster-monitoring-config.yml') }}"

- name:  Enable Autoscaler
  block:
    - name: Get Infrastructure Name
      k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info
    - name: Create ClusterAutoscaler
      k8s:
        state: present
        definition:
          apiVersion: autoscaling.openshift.io/v1
          kind: ClusterAutoscaler
          metadata:
            name: default
          spec:
            podPriorityThreshold: -10
            resourceLimits:
              maxNodesTotal: 18
              cores:
                min: 2
                max: 4
              memory:
                min: 8
                max: 16
            scaleDown:
              enabled: true
    - name: Create Infra MachineAutoscaler
      k8s:
        state: present
        definition:
          apiVersion: autoscaling.openshift.io/v1beta1
          kind: MachineAutoscaler
          metadata:
            name: infra-us-east-2{{ item }}
            namespace: openshift-machine-api
          spec:
            minReplicas: 1
            maxReplicas: 3
            scaleTargetRef:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              name: "{{ infra_info.resources[0].status.infrastructureName }}-infra-us-east-2{{ item }}"
      loop: ['a', 'b', 'c']
    - name: Create Worker MachineAutoscaler
      k8s:
        state: present
        definition:
          apiVersion: autoscaling.openshift.io/v1beta1
          kind: MachineAutoscaler
          metadata:
            name: worker-us-east-2{{ item }}
            namespace: openshift-machine-api
          spec:
            minReplicas: 1
            maxReplicas: 2
            scaleTargetRef:
              apiVersion: machine.openshift.io/v1beta1
              kind: MachineSet
              name: "{{ infra_info.resources[0].status.infrastructureName }}-worker-us-east-2{{ item }}"
      loop: ['a', 'b', 'c']

