- name: Get a list of infra nodes
  k8s_info:
    kind: Node
    label_selector:
      - node-role.kubernetes.io/infra
  register: infranode_list

- name: Print infranode list
  debug:
    msg: "{{ infranode_list }}"

