- name: Register system and enable required repos
  block:
    - name: dnf clean all
      command: dnf clean all
    - name: sub-mgr remove all
      command: subscription-manager remove --all
    - name: sub-mgr unregister
      command: subscription-manager unregister
    - name: sub-mgr clean
      command: subscription-manager clean
    - name: Remove katello-ca-consumer-labsat.opentlc.com
      dnf:
        name: katello-ca-consumer-labsat.opentlc.com
        state: absent
    - name: Check for ansible-tower-cli-el7.repo
      stat:
        path: /etc/yum.repos.d/ansible-tower-cli-el7.repo
      register: repo_file
    - name: Copy ansible-tower-cli-el7.repo
      copy:
        src: /etc/yum.repos.d/ansible-tower-cli-el7.repo
        dest: /etc/yum.repos.d/ansible-tower-cli-el7.repo.disabled
        remote_src: yes
      when: repo_file.stat.exists
    - name: Remove ansible-tower-cli-el7.repo
      file:
        path: /etc/yum.repos.d/ansible-tower-cli-el7.repo
        state: absent
    - name: sub-mgr register
      redhat_subscription:
        state: present
        username: rhn-support-alchan
        password: "{{ rhnpasswd }}"
        force_register: yes
        pool_ids: 8a85f99c6c8b9588016c8be0f38a0ee9
    - name: Enable needed repos
      rhsm_repository:
        name:
          - ansible-2-for-rhel-8-x86_64-rpms
          - rhel-8-for-x86_64-supplementary-rpms
          - rhocp-{{ ocpver }}-for-rhel-8-x86_64-rpms
        state: enabled
    - name: dnf clean all
      command: dnf clean all
    - name: dnf install packages
      dnf:
        name:
          - python3-boto3
          - python3-pyyaml
          - python3-openshift
          - python3-requests-oauthlib
          - tree
          - traceroute
          - lsof
          - jq
        state: latest
  tags:
    - reg-host
