- name: set vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: set vi alias
  lineinfile:
    path: ~/.bashrc
    line: 'alias vi=vim'
    insertafter: '^alias mv'

- name: set aws completion
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - "complete -C '/usr/local/aws/bin/aws_completer' aws"

- name: set env vars
  lineinfile:
    path: ~/.bash_profile
    line: "{{ item }}"
  with_items:
    - 'EDITOR=vim'
    - 'VISUAL=vim'
    - 'SSH_KEY_PATH=~/.ssh/cluster-${GUID}-key'
    - 'KUBECONFIG=~/cluster-${GUID}/auth/kubeconfig'
    - 'export EDITOR VISUAL SSH_KEY_PATH KUBECONFIG'

- name: create ~/bin
  file:
    path: ~/bin
    state: directory

- name: get yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
    dest: ~/bin/yq
    mode: '0755'

