- name: set vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: set vi alias
  lineinfile:
    path: ~/.bashrc
    line: 'alias vi=vim'
    insertafter: '^alias mv'

- name: set env vars
  lineinfile:
    path: ~/.bash_profile
    line: "{{ item }}"
  with_items:
    - ''
    - 'EDITOR=vim'
    - 'VISUAL=vim'
    - 'SSH_KEY_PATH=~/.ssh/cluster-{{ guid.stdout }}-key'
    - 'export EDITOR VISUAL SSH_KEY_PATH'
