- name: set vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: set vi alias
  lineinfile:
    path: ~/.bashrc
    line: 'alias vi=vim'
    insertafter: '^alias mv'

- name: replace ge alias
  lineinfile:
    path: ~/.bashrc
    regexp: '^alias ge'
    line: 'alias ge="oc get events --sort-by=.lastTimestamp"'

- name: set jq/yq/rmf alias
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
    insertafter: '^alias ge'
  loop:
    - alias kadm='egrep "web-console|Login"  ~/cluster-${GUID}/.openshift_install.log'
    - alias rmf="yq e 'del(..|select(has(\"managedFields\")).managedFields)' - | less -R"
    - alias yq="yq -C"
    - alias jq="jq -C"
    - alias less="less -X"

- name: set aws completion
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - "complete -C '/usr/local/bin/aws_completer' aws"

- name: replace PATH
  lineinfile:
    path: ~/.bash_profile
    regexp: '^export PATH'
    line: 'export PATH=~/bin:$PATH'

- name: set env vars
  lineinfile:
    path: ~/.bash_profile
    line: "{{ item }}"
  with_items:
    - 'EDITOR=vim'
    - 'VISUAL=vim'
    - 'SSH_KEY_PATH=~/.ssh/cluster-${GUID}-key'
    - 'KUBECONFIG=~/cluster-${GUID}/auth/kubeconfig'
    - 'export EDITOR VISUAL SSH_KEY_PATH KUBECONFIG'

- name: create ~/bin
  file:
    path: ~/bin
    state: directory

- name: get yq
  get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64
    dest: ~/bin/yq
    mode: '0755'

- name: get ssh-bastion ssh.sh
  get_url:
    url: https://raw.githubusercontent.com/eparis/ssh-bastion/master/ssh.sh
    dest: ~/bin/ssh-bastion.sh
    mode: '0755'
